// registry/ui/document0-vue/page-navigation/PageNavigation.vue
<script setup lang="ts">
interface NavItem {
  name: string;
  url: string;
}

defineProps<{
  previous: NavItem | null;
  next: NavItem | null;
}>();
</script>

<template>
  <nav
    v-if="previous || next"
    class="mt-16 flex justify-between gap-4 border-t border-zinc-800 pt-6"
  >
    <div class="flex-1">
      <RouterLink
        v-if="previous"
        :to="previous.url"
        class="group flex flex-col gap-1 text-sm"
      >
        <span class="text-zinc-500 transition-colors group-hover:text-zinc-400"
          >← Previous</span
        >
        <span
          class="font-medium text-zinc-300 transition-colors group-hover:text-white"
          >{{ previous.name }}</span
        >
      </RouterLink>
    </div>
    <div class="flex-1 text-right">
      <RouterLink
        v-if="next"
        :to="next.url"
        class="group flex flex-col items-end gap-1 text-sm"
      >
        <span class="text-zinc-500 transition-colors group-hover:text-zinc-400"
          >Next →</span
        >
        <span
          class="font-medium text-zinc-300 transition-colors group-hover:text-white"
          >{{ next.name }}</span
        >
      </RouterLink>
    </div>
  </nav>
</template>

// apps/docs/components/page-navigation.tsx
import Link from "next/link";

interface NavItem { name: string; url: string }

export function PageNavigation({ previous, next }: { previous: NavItem | null; next: NavItem | null }) {
  if (!previous && !next) return null;
  return (
    <nav className="mt-16 pt-6 border-t border-zinc-800 flex justify-between gap-4">
      <div className="flex-1">
        {previous && (
          <Link href={previous.url} className="group flex flex-col gap-1 text-sm">
            <span className="text-zinc-500 group-hover:text-zinc-400 transition-colors">← Previous</span>
            <span className="font-medium text-zinc-300 group-hover:text-white transition-colors">{previous.name}</span>
          </Link>
        )}
      </div>
      <div className="flex-1 text-right">
        {next && (
          <Link href={next.url} className="group flex flex-col gap-1 text-sm items-end">
            <span className="text-zinc-500 group-hover:text-zinc-400 transition-colors">Next →</span>
            <span className="font-medium text-zinc-300 group-hover:text-white transition-colors">{next.name}</span>
          </Link>
        )}
      </div>
    </nav>
  );
}
