// packages/template/components/page-navigation.tsx
import Link from "next/link";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

interface NavItem {
  name: string;
  url: string;
}

interface PageNavigationProps {
  previous: NavItem | null;
  next: NavItem | null;
}

export function PageNavigation({ previous, next }: PageNavigationProps) {
  if (!previous && !next) return null;

  return (
    <nav aria-label="Page navigation" className="mt-12 grid grid-cols-2 gap-4">
      {previous ? (
        <Link href={previous.url} className="group">
          <Card className="h-full transition-colors hover:bg-accent/50">
            <CardContent className="flex items-center gap-3 p-4">
              <ChevronLeft className="h-4 w-4 shrink-0 text-muted-foreground" />
              <div>
                <p className="text-xs text-muted-foreground">Previous</p>
                <p className="text-sm font-medium">{previous.name}</p>
              </div>
            </CardContent>
          </Card>
        </Link>
      ) : (
        <div />
      )}
      {next ? (
        <Link href={next.url} className="group">
          <Card className="h-full transition-colors hover:bg-accent/50">
            <CardContent className="flex items-center justify-end gap-3 p-4 text-right">
              <div>
                <p className="text-xs text-muted-foreground">Next</p>
                <p className="text-sm font-medium">{next.name}</p>
              </div>
              <ChevronRight className="h-4 w-4 shrink-0 text-muted-foreground" />
            </CardContent>
          </Card>
        </Link>
      ) : (
        <div />
      )}
    </nav>
  );
}

// registry/ui/document0-vue/page-navigation/PageNavigation.vue
<script setup lang="ts">
interface NavItem {
  name: string;
  url: string;
}

defineProps<{
  previous: NavItem | null;
  next: NavItem | null;
}>();
</script>

<template>
  <nav
    v-if="previous || next"
    class="mt-16 flex justify-between gap-4 border-t border-zinc-800 pt-6"
  >
    <div class="flex-1">
      <RouterLink
        v-if="previous"
        :to="previous.url"
        class="group flex flex-col gap-1 text-sm"
      >
        <span class="text-zinc-500 transition-colors group-hover:text-zinc-400"
          >← Previous</span
        >
        <span
          class="font-medium text-zinc-300 transition-colors group-hover:text-white"
          >{{ previous.name }}</span
        >
      </RouterLink>
    </div>
    <div class="flex-1 text-right">
      <RouterLink
        v-if="next"
        :to="next.url"
        class="group flex flex-col items-end gap-1 text-sm"
      >
        <span class="text-zinc-500 transition-colors group-hover:text-zinc-400"
          >Next →</span
        >
        <span
          class="font-medium text-zinc-300 transition-colors group-hover:text-white"
          >{{ next.name }}</span
        >
      </RouterLink>
    </div>
  </nav>
</template>
