// packages/template-nextjs/components/table-of-contents.tsx
"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import type { TocEntry } from "@document0/mdx";

export function TableOfContents({ toc }: { toc: TocEntry[] }) {
  const [activeId, setActiveId] = useState<string>("");

  useEffect(() => {
    function onScroll() {
      let current = "";
      for (const entry of toc) {
        const el = document.getElementById(entry.id);
        if (el) {
          const rect = el.getBoundingClientRect();
          if (rect.top <= 80) current = entry.id;
        }
      }
      setActiveId(current);
    }
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [toc]);

  if (toc.length === 0) return null;

  return (
    <aside className="hidden xl:block w-56 shrink-0 sticky top-14 h-[calc(100vh-3.5rem)]">
      <div className="py-6 pr-2">
        <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          On this page
        </p>
        <ul className="space-y-1">
          {toc.map((entry) => (
            <li key={entry.id} style={{ paddingLeft: `${(entry.depth - 1) * 0.75}rem` }}>
              <a
                href={`#${entry.id}`}
                className={cn(
                  "block py-1 text-sm transition-colors",
                  activeId === entry.id
                    ? "text-foreground font-medium"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                {entry.text}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </aside>
  );
}

// registry/ui/document0-vue/toc/TableOfContents.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";

interface TocEntry {
  id: string;
  text: string;
  depth: number;
}

const props = defineProps<{
  toc: TocEntry[];
}>();

const activeId = ref("");

function updateActive() {
  const atBottom =
    window.innerHeight + window.scrollY >= document.body.scrollHeight - 50;
  if (atBottom && props.toc.length > 0) {
    activeId.value = props.toc[props.toc.length - 1].id;
    return;
  }

  const threshold = 80;
  let current = props.toc.length > 0 ? props.toc[0].id : "";
  for (const { id } of props.toc) {
    const el = document.getElementById(id);
    if (!el) continue;
    if (el.getBoundingClientRect().top <= threshold) {
      current = id;
    }
  }
  activeId.value = current;
}

onMounted(() => {
  updateActive();
  window.addEventListener("scroll", updateActive, { passive: true });
});

onUnmounted(() => {
  window.removeEventListener("scroll", updateActive);
});
</script>

<template>
  <div class="sticky top-20">
    <p class="mb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">
      On this page
    </p>
    <ul class="space-y-1">
      <li
        v-for="entry in toc"
        :key="entry.id"
        :style="{ paddingLeft: `${(entry.depth - 1) * 12}px` }"
      >
        <a
          :href="`#${entry.id}`"
          :class="[
            'block py-0.5 text-sm transition-colors',
            activeId === entry.id
              ? 'text-sky-400 font-medium'
              : 'text-zinc-500 hover:text-zinc-300',
          ]"
        >
          {{ entry.text }}
        </a>
      </li>
    </ul>
  </div>
</template>
