// apps/docs/components/search-dialog.tsx
"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import { useRouter } from "next/navigation";

interface SearchResult {
  title: string;
  description?: string;
  url: string;
  score: number;
}

export function SearchDialog({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchResult[]>([]);
  const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(null);

  useEffect(() => {
    if (open) {
      setQuery("");
      setResults([]);
      setSelected(0);
      setTimeout(() => inputRef.current?.focus(), 0);
    }
  }, [open]);

  const fetchResults = useCallback((q: string) => {
    if (!q.trim()) {
      setResults([]);
      setLoading(false);
      return;
    }
    setLoading(true);
    fetch(`/internal/search?q=${encodeURIComponent(q)}`)
      .then((r) => r.json())
      .then((data: SearchResult[]) => {
        setResults(data);
        setSelected(0);
      })
      .finally(() => setLoading(false));
  }, []);

  const handleChange = (value: string) => {
    setQuery(value);
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => fetchResults(value), 150);
  };

  const navigate = (url: string) => {
    onClose();
    router.push(url);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSelected((s) => Math.min(s + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSelected((s) => Math.max(s - 1, 0));
    } else if (e.key === "Enter" && results[selected]) {
      navigate(results[selected].url);
    } else if (e.key === "Escape") {
      onClose();
    }
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[100]" onClick={onClose}>
      <div className="fixed inset-0 bg-black/60 backdrop-blur-sm" />
      <div className="fixed inset-x-0 top-[15%] mx-auto w-full max-w-lg px-4">
        <div
          className="rounded-xl border border-zinc-800 bg-zinc-900 shadow-2xl overflow-hidden"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-center gap-3 border-b border-zinc-800 px-4">
            <svg
              className="h-4 w-4 shrink-0 text-zinc-500"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <circle cx="11" cy="11" r="8" />
              <path d="m21 21-4.3-4.3" />
            </svg>
            <input
              ref={inputRef}
              type="text"
              value={query}
              onChange={(e) => handleChange(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Search docs..."
              className="flex-1 bg-transparent py-3.5 text-sm text-white placeholder:text-zinc-500 outline-none"
            />
            <kbd className="hidden sm:inline-flex items-center rounded border border-zinc-700 bg-zinc-800 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500">
              ESC
            </kbd>
          </div>
          <div className="max-h-[320px] overflow-y-auto">
            {loading && (
              <div className="px-4 py-8 text-center text-sm text-zinc-500">
                Searching...
              </div>
            )}
            {!loading && query && results.length === 0 && (
              <div className="px-4 py-8 text-center text-sm text-zinc-500">
                No results for &ldquo;{query}&rdquo;
              </div>
            )}
            {!loading && results.length > 0 && (
              <ul className="py-2">
                {results.map((result, i) => (
                  <li key={result.url}>
                    <button
                      type="button"
                      onClick={() => navigate(result.url)}
                      onMouseEnter={() => setSelected(i)}
                      className={[
                        "w-full text-left px-4 py-2.5 flex flex-col gap-0.5 transition-colors",
                        selected === i
                          ? "bg-sky-500/10"
                          : "hover:bg-zinc-800/60",
                      ].join(" ")}
                    >
                      <span
                        className={[
                          "text-sm font-medium",
                          selected === i ? "text-sky-400" : "text-zinc-200",
                        ].join(" ")}
                      >
                        {result.title}
                      </span>
                      {result.description && (
                        <span className="text-xs text-zinc-500 line-clamp-1">
                          {result.description}
                        </span>
                      )}
                    </button>
                  </li>
                ))}
              </ul>
            )}
            {!loading && !query && (
              <div className="px-4 py-8 text-center text-sm text-zinc-500">
                Type to search documentation
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// registry/ui/document0-vue/search-dialog/SearchDialog.vue
<script setup lang="ts">
import { ref, watch, nextTick, onMounted, onUnmounted } from "vue";
import { useRouter } from "vue-router";

interface SearchResult {
  title: string;
  description?: string;
  url: string;
  score: number;
}

const props = defineProps<{
  open: boolean;
}>();

const emit = defineEmits<{
  close: [];
}>();

const query = ref("");
const results = ref<SearchResult[]>([]);
const loading = ref(false);
const selected = ref(0);
const inputEl = ref<HTMLInputElement | null>(null);
const router = useRouter();
let debounceTimer: ReturnType<typeof setTimeout> | null = null;

watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) {
      query.value = "";
      results.value = [];
      selected.value = 0;
      nextTick(() => inputEl.value?.focus());
    }
  }
);

function fetchResults(q: string) {
  if (!q.trim()) {
    results.value = [];
    loading.value = false;
    return;
  }
  loading.value = true;
  fetch(`/internal/search?q=${encodeURIComponent(q)}`)
    .then((r) => r.json())
    .then((data: SearchResult[]) => {
      results.value = data;
      selected.value = 0;
    })
    .finally(() => {
      loading.value = false;
    });
}

function handleInput(e: Event) {
  const value = (e.target as HTMLInputElement).value;
  query.value = value;
  if (debounceTimer) clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => fetchResults(value), 150);
}

function navigate(url: string) {
  emit("close");
  router.push(url);
}

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === "ArrowDown") {
    e.preventDefault();
    selected.value = Math.min(selected.value + 1, results.value.length - 1);
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    selected.value = Math.max(selected.value - 1, 0);
  } else if (e.key === "Enter" && results.value[selected.value]) {
    navigate(results.value[selected.value].url);
  } else if (e.key === "Escape") {
    emit("close");
  }
}
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="fixed inset-0 z-[100]" @click="emit('close')">
      <div class="fixed inset-0 bg-black/60 backdrop-blur-sm" />
      <div class="fixed inset-x-0 top-[15%] mx-auto w-full max-w-lg px-4">
        <div
          class="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900 shadow-2xl"
          @click.stop
        >
          <div class="flex items-center gap-3 border-b border-zinc-800 px-4">
            <svg
              class="h-4 w-4 shrink-0 text-zinc-500"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <circle cx="11" cy="11" r="8" />
              <path d="m21 21-4.3-4.3" />
            </svg>
            <input
              ref="inputEl"
              type="text"
              :value="query"
              placeholder="Search docs..."
              class="flex-1 bg-transparent py-3.5 text-sm text-white outline-none placeholder:text-zinc-500"
              @input="handleInput"
              @keydown="handleKeyDown"
            />
            <kbd
              class="hidden items-center rounded border border-zinc-700 bg-zinc-800 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500 sm:inline-flex"
            >
              ESC
            </kbd>
          </div>
          <div class="max-h-[320px] overflow-y-auto">
            <div
              v-if="loading"
              class="px-4 py-8 text-center text-sm text-zinc-500"
            >
              Searching...
            </div>
            <div
              v-else-if="query && results.length === 0"
              class="px-4 py-8 text-center text-sm text-zinc-500"
            >
              No results for "{{ query }}"
            </div>
            <ul v-else-if="results.length > 0" class="py-2">
              <li v-for="(result, i) in results" :key="result.url">
                <button
                  type="button"
                  :class="[
                    'flex w-full flex-col gap-0.5 px-4 py-2.5 text-left transition-colors',
                    selected === i
                      ? 'bg-sky-500/10'
                      : 'hover:bg-zinc-800/60',
                  ]"
                  @click="navigate(result.url)"
                  @mouseenter="selected = i"
                >
                  <span
                    :class="[
                      'text-sm font-medium',
                      selected === i ? 'text-sky-400' : 'text-zinc-200',
                    ]"
                  >
                    {{ result.title }}
                  </span>
                  <span
                    v-if="result.description"
                    class="line-clamp-1 text-xs text-zinc-500"
                  >
                    {{ result.description }}
                  </span>
                </button>
              </li>
            </ul>
            <div
              v-else
              class="px-4 py-8 text-center text-sm text-zinc-500"
            >
              Type to search documentation
            </div>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>
