// registry/ui/document0-vue/breadcrumbs/Breadcrumbs.vue
<script setup lang="ts">
interface BreadcrumbItem {
  name: string;
  url?: string;
}

defineProps<{
  items: BreadcrumbItem[];
}>();
</script>

<template>
  <nav v-if="items.length > 1" aria-label="Breadcrumb" class="mb-4">
    <ol class="flex flex-wrap items-center gap-1.5 text-sm text-zinc-500">
      <li
        v-for="(item, i) in items"
        :key="i"
        class="flex items-center gap-1.5"
      >
        <span v-if="i > 0" class="text-zinc-700">/</span>
        <RouterLink
          v-if="i < items.length - 1 && item.url"
          :to="item.url"
          class="hover:text-zinc-300 transition-colors"
        >
          {{ item.name }}
        </RouterLink>
        <span v-else class="text-zinc-400">{{ item.name }}</span>
      </li>
    </ol>
  </nav>
</template>

// registry/ui/document0/breadcrumbs/Breadcrumbs.tsx
import Link from "next/link";
import type { BreadcrumbItem } from "@document0/core";

/**
 * Breadcrumb navigation showing current page path.
 *
 * Usage:
 * ```tsx
 * import { Breadcrumbs } from "@/components/document0/breadcrumbs/Breadcrumbs";
 * import { getBreadcrumbs } from "@document0/core";
 *
 * // In your page component:
 * const tree = getPageTree();
 * const breadcrumbs = getBreadcrumbs(tree, page.url);
 *
 * return <Breadcrumbs items={breadcrumbs} />;
 * ```
 */
export function Breadcrumbs({ items }: { items: BreadcrumbItem[] }) {
  if (items.length <= 1) return null;
  return (
    <nav aria-label="Breadcrumb" className="mb-4">
      <ol className="flex flex-wrap items-center gap-1.5 text-sm text-zinc-500">
        {items.map((item, i) => (
          <li key={i} className="flex items-center gap-1.5">
            {i > 0 && <span className="text-zinc-700">/</span>}
            {i < items.length - 1 && item.url ? (
              <Link href={item.url} className="hover:text-zinc-300 transition-colors">
                {item.name}
              </Link>
            ) : (
              <span className="text-zinc-400">{item.name}</span>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}
